version: '3.8'

services:
  web:
    build: .
    container_name: jenkins_task_app
    ports:
      - "9090:5000"  # Expose app on port 9090
    volumes:
      - .:/app       # Mount current project directory into container
    restart: always

volumes:
  db-data: